# Author :- Dheeraj Choudhary
AWSTemplateFormatVersion: 2010-09-09
Description: Create custom VPC with custom CIDR Block and enable dnshostname,dnssupport
Resources:
  CustomVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: CutomVPC
Outputs:
  outputCustomVPC:
    Description: A reference to the created security group
    Value: !Ref CustomVPC
